const portfolioProjectCatalog = {
  demoreel: {
    slug: "demoreel",
    title: "Demoreel",
    subtitle: "Sélection de projets",
    type: "Demoreel",
    role: "Montage et motion design",
    client: {},
    vimeo: "https://player.vimeo.com/video/832654295?dnt=1",
    text: [
      "Devil’s Sweet Tooth | Live in concrete | Kee Avil — montage",
      "Beyrouth plusieurs fois — réalisation, montage, colorisation",
      "Zug Island — montage",
      "Exobouchées 2 : Terre 2.0 — animation",
      "Exobouchées 5 : Les téléscopes du futur — animation",
      "Seuls | zouz — montage et colorisation",
      "See, my shadow | Live in concrete | Kee Avil — montage",
      "Évincés : Les aînés contre-attaquent — montage, motion design",
      "Perspective contractée : Le Tombeau de Gilles Groulx — montage",
      "Zéro Stress | Naomi — montage",
      "Chroniques de la vie ordinaire : Canal St-Martin — montage",
      "Chroniques de la vie ordinaire : Buttes-Chaumont — montage",
      "Chroniques de la vie ordinaire : Strasbourg – St-Denis — montage",
      "Division Couleur : DémoReel 2022 — motion design, vfx",
      "Cité mémoire | MEH | L’église de la Malbaie — graphisme, motion design, montage",
      "Come a Bit Closer (teaser) — montage",
      "Prix du Gouverneur général pour les arts et spectacles 2018 (trailer) — montage",
      "Come a Bit Closer : Tangente 2021 — réalisation, caméra, montage",
      "Bienvenue au Biodôme de Montréal — montage et colorisation",
      "HHHH | Live in concrete | Kee Avil — montage",
    ],
    credits: [{ label: "Montage et motion design", value: "Jérémie Carvalho" }],
    views: ["projects", "montage", "motion"],
    palette: { base: "#1d1e24", accent: "#99a0ba", infoStart: "#313749", infoEnd: "#08090d" },
    locales: {
      en: {
        title: "Demo Reel",
        subtitle: "Selected work",
        text: [
          "A curated reel bringing together a selection of editing, motion design, and post-production work.",
          "This project card acts as an entry point into the broader body of work featured on the site. It can later be expanded with the final reel, a more precise shot list, and fuller credits if needed.",
        ],
      },
    },
  },
  "langlois-dragonfly": {
    slug: "langlois-dragonfly",
    title: "Robert Langlois - Dragonfly",
    subtitle: "Vidéoclip, 2026",
    type: "Vidéoclip",
    role: "Colorisation et effets visuels",
    client: {},
    vimeo: "https://player.vimeo.com/video/1223384431",
    text: [],
    credits: [
      { label: "Réalisation", value: "Philippe Léonard" },
      { label: "Colorisation et effets visuels", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "motion"],
    palette: { base: "#2a2726", accent: "#7c7b7b", infoStart: "#1a1e57", infoEnd: "#111111" },
  },
  "onf-bww": {
    slug: "onf-bww",
    title: "Bread Will Walk",
    subtitle: "Bande-annonce, 2026",
    type: "Bande-annonce",
    role: "Montage",
    client: { label: "Production", value: "ONF" },
    vimeo: "https://player.vimeo.com/video/1223445570",
    text: ["« Une sœur dévouée prend la fuite avec son frère métamorphosé en étrange créature de pain. Une foule affamée les pourchasse. Les rues s’emmêlent, la raison s’émiette. L’amour peut-il l’emporter sur la faim ? » - site internet de l'ONF"],
    credits: [
      { label: "Réalisation", value: "Alex Boya" },
      { label: "Coordination bande-annonce", value: "Marion Duhaime-Morissette" },
      { label: "Montage bande-annonce", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "montage"],
    palette: { base: "#2a2726", accent: "#a78b75", infoStart: "#4d4036", infoEnd: "#111111" },
  },
  "onf-paradaiz": {
    slug: "onf-paradaiz",
    title: "Paradaïz",
    subtitle: "Bande-annonce, 2026",
    type: "Bande-annonce",
    role: "Montage",
    client: { label: "Production", value: "ONF" },
    vimeo: "https://player.vimeo.com/video/1223444825",
    text: ["« Bienvenue à Paradaïz : le lieu des limaces sans toit, des murs criblés de balles, des cigarettes qui s’enchaînent et des tomates explosives.» - site internet de l'ONF"],
    credits: [
      { label: "Réalisation", value: "Matea Radic" },
      { label: "Montage bande-annonce", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "montage"],
    palette: { base: "#2a2726", accent: "#a78b75", infoStart: "#4d4036", infoEnd: "#111111" },
  },
  "pc-cdn": {
    slug: "pc-cdn",
    title: "Crimes du nord",
    subtitle: "Série documentaire, 2026",
    type: "Série documentaire",
    role: "Motion design et conception graphique",
    client: { label: "Production", value: "Casadel Films / Historia" },
    vimeo: "https://player.vimeo.com/video/1223399273",
    text: ["« Montréal est considérée comme une petite ville à l’échelle planétaire et, pourtant, elle jouit d’une grande réputation dans l’univers du crime organisé mondial. Comment son histoire criminelle reflète-t-elle son ADN? À la croisée des chemins entre l’Europe et l’Amérique, le crime montréalais a été façonné par de nombreuses vagues d’immigration, une situation géographique unique et des mouvements sociaux importants.» - site internet d'Historia"],
    credits: [
      { label: "Réalisation", value: "Alexis Chartrand" },
      { label: "Production", value: "Patrick Francke-Sirois" },
      { label: "Montage", value: "Cédric Froment" },
      { label: "Motion design et effets spéciaux", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "motion"],
    palette: { base: "#2a2726", accent: "#7c7b7b", infoStart: "#1a1e57", infoEnd: "#111111" },
  },
  "onf-tgwcp": {
    slug: "onf-tgwcp",
    title: "La jeune fille qui pleurait des perles",
    subtitle: "Bande-annonce, 2025",
    type: "Bande-annonce",
    role: "Montage",
    client: { label: "Production", value: "ONF" },
    vimeo: "https://player.vimeo.com/video/1119834616",
    text: ["« Épris d’une jeune fille dont les pleurs se transforment en perles, un garçon miséreux est confronté à un cruel dilemme entre l’amour et la fortune.» - site internet de l'ONF"],
    credits: [
      { label: "Réalisation", value: "Chris Lavis, Maciek Szczerbowski" },
      { label: "Montage bande-annonce", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "montage"],
    palette: { base: "#2a2726", accent: "#a78b75", infoStart: "#4d4036", infoEnd: "#111111" },
  },
  "stephanie-boulay": {
    slug: "stephanie-boulay",
    title: "Stéphanie Boulay",
    subtitle: "Vidéoclip, 2025",
    type: "Vidéoclip",
    role: "Montage",
    client: { label: "Label", value: "Simone records" },
    text: ["La chanson est parue sur l'album solo de Stéphanie Boulay, intitulé « Est-ce que quelqu’un me voit? ». Et oui, j'ai pleuré quelques fois moi aussi durant le montage de ce beau vidéoclip."],
    credits: [
      { label: "Réalisation", value: "Clara L'heureux-Garcia" },
      { label: "Montage", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "Music video created for Stéphanie Boulay. I handled the edit, with a strong focus on rhythm, breathing room, and the progression of the story.",
          "This card currently reflects the information available on the existing site and can be expanded later with the final media assets.",
        ],
      },
    },
    views: ["projects", "montage"],
    palette: { base: "#2a2726", accent: "#a78b75", infoStart: "#4d4036", infoEnd: "#111111" },
  },
  "donner-le-gout": {
    slug: "donner-le-gout",
    title: "Donner le goût",
    subtitle: "Série culinaire, 2025",
    type: "Série culinaire",
    role: "Motion design",
    client: { label: "Diffuseur", value: "Télé-Québec" },
    vimeo: "https://player.vimeo.com/video/1082653408?h=d5877f012e",
    text: [
      "Dans ce rafraîchissant magazine culturel de Télé-Québec, Hélène Bourgeois-Leclerc nous fait découvrir la diversité culturelle au Québec en visitant les cuisines de restaurants à travers la province.",
      "En partant de l'identité visuelle conçue par l'équipe de Maubau, j'ai développé le motion design pour répondre au rythme très catchy du montage, avec des mouvements brusques qui se terminent dans la douceur avec un petit oumf.",
      "Le mandat visait quelque chose de simple, efficace et facilement déclinable par l'équipe du montage online. J'ai donc livré une poignée de templates faits maison, conçus dans After Effects avec des expressions pour que tout demeure éditable dans Adobe Premiere tout en conservant les mêmes mouvements d'un contexte à l'autre.",
    ],
    credits: [
      { label: "Réalisation", value: "Xavier Havitov" },
      { label: "Production", value: "Juliette Provost-Dubois, Hélène Villemure, Patrick Franke-Sirois" },
      { label: "Design graphique", value: "Maubau" },
      { label: "Motion design", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "motion"],
    palette: { base: "#201d18", accent: "#d6aa67", infoStart: "#49311c", infoEnd: "#100905" },
    locales: {
      en: {
        title: "Donner le goût",
        subtitle: "Culinary series, 2025",
        type: "Culinary series",
        role: "Motion design",
        client: { label: "Broadcaster", value: "Télé-Québec" },
        text: [
          "In this vibrant Télé-Québec cultural food series, Hélène Bourgeois-Leclerc introduces the cultural diversity of Quebec through restaurant kitchens across the province.",
          "Starting from the visual identity designed by Maubau, I developed the motion design to match the show's catchy editorial rhythm, using sharp movements that resolve into something softer and warmer.",
          "The mandate called for something simple, efficient, and easy for the online editing team to reuse. I therefore delivered a set of custom templates built in After Effects with expressions so that everything remained editable directly in Adobe Premiere while preserving the same motion logic in every context.",
        ],
        credits: [
          { label: "Direction", value: "Xavier Havitov" },
          { label: "Production", value: "Juliette Provost-Dubois, Hélène Villemure, Patrick Franke-Sirois" },
          { label: "Graphic design", value: "Maubau" },
          { label: "Motion design", value: "Jérémie Carvalho" },
        ],
      },
    },
  },
  "onf-ledl": {
    slug: "onf-ledl",
    title: "Les enfants du large",
    subtitle: "Bande-annonce, 2025",
    type: "Bande-annonce",
    role: "Montage",
    client: { label: "Production", value: "ONF" },
    vimeo: "https://player.vimeo.com/video/1231003987",
    text: ["« Virginia Tangvald navigue sur les eaux troubles de son histoire familiale pour résoudre le mystère entourant la disparition de son frère et le naufrage de son père, le célèbre marin Peter Tangvald.» - site internet de l'ONF"],
    credits: [
      { label: "Réalisation", value: "Virginia Tangvald" },
      { label: "Montage bande-annonce", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "montage"],
    palette: { base: "#2a2726", accent: "#a78b75", infoStart: "#4d4036", infoEnd: "#111111" },
  },
  elisapie: {
    slug: "elisapie",
    title: "Elisapie",
    subtitle: "Vidéoclip, 2024",
    type: "Vidéoclip",
    role: "Montage, colorisation et effets visuels",
    client: { label: "Label", value: "Bonsound" },
    vimeo: "https://player.vimeo.com/video/1053402314?h=ee18653680",
    text: [
      "Quviasukkuvit est une relecture en inuktitut de la chanson If It Makes You Happy, portée par une esthétique de « Hollywood hangover ».",
      "Le projet était pour moi l'occasion de brouiller les limites entre colorisation et effets visuels, afin de faire dialoguer les séquences de chorégraphie en studio avec les paysages intégrés au cadre.",
      "Le montage a été fait sur DaVinci Resolve, puis retravaillé dans After Effects avant une dernière passe de colorisation pour préciser ce rendu doux, légèrement imprécis et volontairement distorsionné.",
    ],
    credits: [
      { label: "Réalisation", value: "Philippe Léonard" },
      { label: "Montage, colorisation et effets visuels", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "Quviasukkuvit is an Inuktitut reinterpretation of If It Makes You Happy, built around a soft, slightly distorted Hollywood-hangover aesthetic.",
          "For this project, I blurred the line between color work and visual effects to connect studio choreography with landscapes composited into the frame.",
          "The edit was assembled in DaVinci Resolve, reworked in After Effects, and finalized through a dedicated color pass to shape the dreamy, intentionally imperfect finish.",
        ],
      },
    },
    views: ["projects", "montage"],
    palette: { base: "#1f2a31", accent: "#7aa1b5", infoStart: "#21313e", infoEnd: "#0a0d11" },
  },
  "frank-bourassa": {
    slug: "frank-bourassa",
    title: "Frank Bourassa",
    subtitle: "Série documentaire, 2023",
    type: "Série documentaire",
    role: "Motion design et effets spéciaux",
    client: { label: "Diffuseur", value: "Crave" },
    vimeo: "https://player.vimeo.com/video/1082652788?h=223a1e7cb9",
    text: [
      "Frank Bourassa et ses faux millions raconte en trois épisodes l'histoire du faussaire de Trois-Rivières et de l'un des plus importants réseaux de faux billets au pays.",
      "Pour intégrer les preuves, les photographies et les éléments numériques, j'ai développé dans After Effects un pipeline permettant d'animer ces matériaux dans un espace 3D cohérent avec l'esthétique sombre du tournage.",
      "Le travail a aussi consisté à traiter les images d'écrans et de caméras de surveillance comme des objets filmés, afin de dynamiser des sources visuelles de qualité variable et de les harmoniser avec la séquence d'ouverture créée par Simon Meloche.",
    ],
    credits: [
      { label: "Réalisation", value: "Alexis Chartrand" },
      { label: "Production", value: "Patrick Francke-Sirois, David Francke-Robitaille" },
      { label: "Direction de la photographie", value: "Thierry Sirois, Louis Turcotte" },
      { label: "Montage", value: "Louis Chevalier" },
      { label: "Motion design et effets spéciaux", value: "Jérémie Carvalho" },
      { label: "Motion design additionnel", value: "Simon Meloche (Muxmo)" },
    ],
    locales: {
      en: {
        text: [
          "Frank Bourassa et ses faux millions tells the story of a Trois-Rivières counterfeiter and one of the most significant fake-bill networks in the country.",
          "To integrate evidence, stills, and digital materials, I built an After Effects pipeline that animated those elements in a 3D space aligned with the series’ dark visual language.",
          "Part of the work also involved treating screen captures and surveillance footage as filmed objects, helping weaker source material feel cinematic and consistent with the opening sequence.",
        ],
      },
    },
    views: ["projects", "motion"],
    palette: { base: "#2b221d", accent: "#d28b55", infoStart: "#4c3422", infoEnd: "#120d09" },
  },
  "beautes-rebelles": {
    slug: "beautes-rebelles",
    title: "Beautés rebelles",
    subtitle: "Série documentaire, 2024",
    type: "Série documentaire",
    role: "Conception graphique et motion design",
    client: { label: "Diffuseur", value: "TV5" },
    vimeo: "https://player.vimeo.com/video/1082652587?h=4f1735eed5",
    text: [
      "Dans Beautés rebelles, Carla Beauvais parcourt le monde pour rencontrer des concours de beauté mettant de l'avant des personnes marginalisées et reconfigurant les normes qui définissent la beauté.",
      "La conception graphique cherchait à conjuguer élégance et rugosité, en travaillant des couleurs pastel, des éclats, des accidents, du grain et des textures capables de prolonger les intentions du projet.",
      "Cette série a été un terrain fort pour pousser le développement de luminosités et de textures uniques, pensées pour dynamiser les transitions et l'enchaînement des plans.",
    ],
    credits: [
      { label: "Réalisation", value: "Alexis B. Martin" },
      { label: "Idée originale", value: "Alix Dufresne" },
      { label: "Animation", value: "Carla Beauvais" },
      { label: "Production", value: "Caroline Bergoin, Patrick Francke-Sirois" },
      { label: "Conception graphique et motion design", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "In Beautés rebelles, Carla Beauvais travels the world to meet pageants that center marginalized people and challenge conventional ideas of beauty.",
          "The design direction aimed to balance elegance and roughness through pastel tones, glints, grain, textures, and visual accidents that extended the spirit of the series.",
          "It became a strong playground for building custom textures and luminosity treatments designed to energize transitions and shot flow.",
        ],
      },
    },
    views: ["projects", "motion"],
    palette: { base: "#251d29", accent: "#b68ccf", infoStart: "#41314d", infoEnd: "#0f0a12" },
  },
  "prison-esprit-saint": {
    slug: "prison-esprit-saint",
    title: "La prison de l'Esprit-Saint",
    subtitle: "Série documentaire, 2024",
    type: "Série documentaire",
    role: "Conception graphique et motion design",
    client: { label: "Diffuseur", value: "Crave" },
    vimeo: "https://player.vimeo.com/video/1082651792?h=ccc23b56c3",
    text: [
      "Cette série documentaire issue du journalisme d'enquête suit Marie-Christine Bergeron à la rencontre d'anciens membres de la Mission de l'Esprit-Saint.",
      "Le parti pris typographique reposait sur une dichotomie entre deux régimes de vérité: d'un côté un langage plus archaïque et obscurantiste, de l'autre un registre journalistique plus sobre et actuel.",
      "Le graphisme et le motion design jouent sur les couches, la transparence, la lumière et la profondeur, avec un look développé dans After Effects puis consolidé par une passe de colorisation dans DaVinci Resolve.",
    ],
    credits: [
      { label: "Réalisation", value: "Isabelle Tincler" },
      { label: "Animation", value: "Marie-Christine Bergeron" },
      { label: "Production", value: "Maxime Landry" },
      { label: "Conception graphique et motion design", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "This investigative documentary series follows Marie-Christine Bergeron as she meets former members of the Mission de l'Esprit-Saint.",
          "The typographic approach was built around a tension between two systems of truth: an archaic, obscurantist visual language on one side and a more sober journalistic register on the other.",
          "The design and motion work relies on layers, transparency, light, and depth, developed in After Effects and refined through a final color pass in DaVinci Resolve.",
        ],
      },
    },
    views: ["projects", "motion"],
    palette: { base: "#202226", accent: "#9da6b0", infoStart: "#343a43", infoEnd: "#0c0f14" },
  },
  "hanging-on-a-string": {
    slug: "hanging-on-a-string",
    title: "Hanging on a String",
    subtitle: "Vidéoclip, 2024",
    type: "Vidéoclip",
    role: "Animation",
    client: {},
    vimeo: "https://player.vimeo.com/video/1086047361",
    text: ["Premier single de l'album du même nom, « Hanging on a String » est un vidéoclip réalisé par Annick Jean."],
    credits: [
      { label: "Réalisation", value: "Annick Jean" },
      { label: "Direction artistique", value: "Rodolphe St-Gelais" },
      { label: "Animation", value: "Rodolphe St-Gelais, Jérémie Carvalho, Max Vannienschoot" },
    ],
    locales: {
      en: {
        text: [
          "Project card prepared from the information currently available in the CV section of the original site.",
          "The piece is listed as a music video for Steve Hill, with a 2D animation mandate. Media and process details can be added in a later pass.",
        ],
      },
    },
    views: ["projects", "motion"],
    palette: { base: "#251819", accent: "#c46d70", infoStart: "#4b2c30", infoEnd: "#12090a" },
  },
  "zug-island": {
    slug: "zug-island",
    title: "Zug Island",
    subtitle: "Court-métrage documentaire, 2022 · 22 min",
    type: "Court-métrage documentaire",
    role: "Montage",
    client: { label: "Distributeur", value: "Les Films du 3 mars" },
    vimeo: "https://player.vimeo.com/video/1082651964?h=49b988fb41",
    text: ["« En quête d’un son mystérieux, un preneur de son fait la rencontre des habitants d’un quartier à l’abandon. » - site internet des Films du 3 mars"],
    credits: [
      { label: "Réalisation", value: "Nicolas Lachapelle" },
      { label: "Production", value: "Guillaume Collin, Nicolas Lachapelle" },
      { label: "Colorisation", value: "Laurence Messier-Moreau" },
      { label: "Montage", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "Documentary short directed by Nicolas Lachapelle and written with Tiago Mc Nicoll Castro Lopes.",
          "I handled the edit, focusing on structure, sequence flow, and the balance between observation and dramatic progression.",
        ],
      },
    },
    views: ["projects", "montage"],
    palette: { base: "#1d2527", accent: "#6fa0a2", infoStart: "#253e42", infoEnd: "#0c1111" },
  },
  evinces: {
    slug: "evinces",
    title: "Évincés",
    subtitle: "Série documentaire, 2023",
    type: "Série documentaire",
    role: "Montage et motion design additionnel",
    client: { label: "Diffuseur", value: "Crave/Noovo" },
    vimeo: "https://player.vimeo.com/video/1082653574?h=61a83c7eda",
    text: [
      "Évincés retrace la lutte des aînés de la résidence Mont-Carmel après la distribution d'avis d'éviction, dans une démarche à la fois politique, intime et profondément collective.",
      "Avec plus de vingt entrevues et plus de quatre-vingts heures de matériel, le montage s'est étalé sur plusieurs mois pour faire émerger une progression claire de l'enquête.",
      "Afin d'appuyer cette enquête autrement que par de simples captures d'écran, j'ai intégré dans After Effects des articles et documents en 3D, avec flous et mouvements de caméra, pour prolonger l'approche documentaire par un travail graphique discret mais structurant.",
    ],
    credits: [
      { label: "Réalisation", value: "Alexis Chartrand" },
      { label: "Animation", value: "Noémi Mercier" },
      { label: "Production", value: "Patrick Francke-Sirois, Juliette Provost-Dubois, Noémi Mercier" },
      { label: "Montage et motion design additionnel", value: "Jérémie Carvalho" },
      { label: "Montage additionnel", value: "Louis Chevalier" },
      { label: "Motion design", value: "Bechir Mogaadi" },
    ],
    locales: {
      en: {
        text: [
          "Évincés follows the fight led by the seniors of Résidence Mont-Carmel after receiving eviction notices, through a story that is political, intimate, and collective at once.",
          "With more than twenty interviews and over eighty hours of material, the edit stretched over several months to build a clear investigative progression.",
          "To support the investigation beyond simple screenshots, I integrated articles and documents in 3D inside After Effects, extending the documentary language through discreet but structuring graphic work.",
        ],
      },
    },
    views: ["projects", "montage"],
    palette: { base: "#2a2420", accent: "#b39374", infoStart: "#42342a", infoEnd: "#110c09" },
  },
  "tout-doux": {
    slug: "tout-doux",
    title: "Tout doux",
    subtitle: "Campagne publicitaire, 2023",
    type: "Campagne publicitaire",
    role: "Motion design",
    client: { label: "Production", value: "Parade" },
    vimeo: "https://player.vimeo.com/video/890120953?h=eab5981268",
    text: ["Projet publicitaire réalisé pour Claude Bégin avec Parade. J'y ai assuré le motion design en continuité avec le montage et la colorisation du projet."],
    credits: [
      { label: "Réalisation / montage", value: "Phil Chagnon" },
      { label: "Colorisation", value: "Olivier Séguin-Dang" },
      { label: "Motion design", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "Advertising project created for Claude Bégin with Parade. I handled the motion design in continuity with the editing and color treatment of the piece.",
          "For now, the card reflects the credits available on the original site and can later be expanded with stills and process details.",
        ],
      },
    },
    views: ["projects", "motion"],
    palette: { base: "#1f2028", accent: "#8f98d3", infoStart: "#2f3351", infoEnd: "#0d0f17" },
  },
  "ascension-pour-cafe-chaud": {
    slug: "ascension-pour-cafe-chaud",
    title: "Ascension pour café chaud",
    subtitle: "Motion design, 2023",
    type: "Motion design",
    role: "Habillage graphique",
    client: {},
    vimeo: "https://player.vimeo.com/video/881523758",
    text: ["Illustrateur et ami, Philmath a concentré son univers créatif autour des choses qu’il aime, soit le café, le jazz et le vélo. Dans le soucis de développer cet art de vivre, l’été 2023 fût pour nous l’occasion de succéder les affogatos, les discussions et les parties d’échec, tout en élaborant de petits projets d’animations. Cette vidéo en fait parti."],
    credits: [
      { label: "Animation", value: "Jérémie Carvalho" },
      { label: "Illustration et voix", value: "Philmath" },
    ],
    locales: {
      en: {
        text: [
          "Project card prepared from the information currently available in the site's live selection.",
          "The piece remains in the structure to prepare the future integration of final media and detailed credits.",
        ],
      },
    },
    views: ["projects", "motion"],
    palette: { base: "#261f1a", accent: "#cc9e67", infoStart: "#463120", infoEnd: "#110a06" },
  },
  zouz: {
    slug: "zouz",
    title: "zouz - Seuls",
    subtitle: "Vidéoclip, 2023",
    type: "Vidéoclip",
    role: "Montage",
    client: { label: "Label", value: "Lazy At Work" },
    vimeo: "https://player.vimeo.com/video/1230974666",
    text: [],
    credits: [
      { label: "Réalisation", value: "Philippe Léonard" },
      { label: "Montage et colorisation", value: "Jérémie Carvalho" },
    ],
    views: ["projects", "montage"],
    palette: { base: "#222127", accent: "#9d8ac0", infoStart: "#362f45", infoEnd: "#0f0c12" },
  },
  "chroniques-vie-ordinaire": {
    slug: "chroniques-vie-ordinaire",
    title: "Chroniques de la vie ordinaire",
    subtitle: "Série documentaire, 2022",
    type: "Série documentaire",
    role: "Montage",
    client: { label: "Diffuseur", value: "TV5" },
    text: [
      "Après un premier cycle montréalais, Amélie Hardy poursuit Chroniques de la vie ordinaire à travers trois quartiers de Paris, dans une forme courte et intimiste.",
      "J'y ai assuré le montage, avec un travail orienté vers la lisibilité, la continuité entre les épisodes et la préservation de la sensibilité propre à chaque rencontre.",
    ],
    credits: [
      { label: "Réalisation", value: "Amélie Hardy" },
      { label: "Production", value: "Patrick Francke-Sirois" },
      { label: "Direction de la photographie", value: "Émile Desroches-Larouche" },
      { label: "Montage", value: "Jérémie Carvalho" },
    ],
    locales: {
      en: {
        text: [
          "After a first cycle set in Montreal, Amélie Hardy continues Chroniques de la vie ordinaire across three Paris neighborhoods in a short and intimate format.",
          "I handled the editing, with an emphasis on clarity, continuity across episodes, and the preservation of each encounter’s sensitivity.",
        ],
      },
    },
    views: ["projects", "montage"],
    palette: { base: "#222127", accent: "#9d8ac0", infoStart: "#362f45", infoEnd: "#0f0c12" },
  },
  "naomi-zero-stress": {
    slug: "naomi-zero-stress",
    title: "Naomi - Zéro stress",
    subtitle: "Vidéoclip, 2021",
    type: "Vidéoclip",
    role: "Montage",
    client: { label: "Label", value: "Bravo Musique" },
    text: [],
    credits: [{ label: "Montage", value: "Jérémie Carvalho" }],
    locales: {
      en: {
        text: [
          "Project card prepared from the information currently available in the CV section of the original site.",
          "The piece is listed as a music video produced with Bravo Musique, with an editing mandate. Media and detailed credits can be added in a later pass.",
        ],
      },
    },
    views: ["projects", "montage"],
    palette: { base: "#231b1c", accent: "#dd7e8a", infoStart: "#45252b", infoEnd: "#100708" },
  },
};

if (typeof window !== "undefined") {
  window.portfolioProjectCatalog = portfolioProjectCatalog;
}

if (typeof module !== "undefined") {
  module.exports = portfolioProjectCatalog;
}
